### ISSUE TITLE
self.auth_interactive_dumb parameter error

### ISSUE THREAD

**Issue by richardxd** [takuma-yoneda/lmn#1]
Hello,

I installed lmn but there seems to be a bug with the self.auth_interactive_dumb parameter: 

lmn run tticslurm -- python test.py
INFO:lmn: Project name     : model
INFO:lmn: Project directory: /Users/username/test
INFO:lmn: Syncing code... (username@slurm.ttic.edu:/home-nfs/username/username/model/code/)
INFO:lmn: Sync finished!
Traceback (most recent call last):
  File "/Users/username/Library/Python/3.11/bin/lmn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/username/Library/Python/3.11/lib/python/site-packages/lmn/cli/__init__.py", line 84, in main
    core(args)
  File "/Users/username/Library/Python/3.11/lib/python/site-packages/lmn/cli/__init__.py", line 76, in core
    parsed.handler(project, remote_conf, parsed, preset_conf)
  File "/Users/username/Library/Python/3.11/lib/python/site-packages/lmn/cli/run.py", line 375, in handler
    ssh_client = CLISSHClient(machine.remote_conf)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Library/Python/3.11/lib/python/site-packages/lmn/machine.py", line 60, in __init__
    self.conn = self.remote_conf.get_connection()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Library/Python/3.11/lib/python/site-packages/lmn/machine.py", line 40, in get_connection
    if self.auth_interactive_dumb:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RemoteConfig' object has no attribute 'auth_interactive_dumb'

**Comment by takuma-yoneda** [comment]
Whoops sorry I didn't attempt to close this!

**Comment by takuma-yoneda** [comment]
@richardxd 
I've just released a new version (v0.3.1) including the fix. Can you try with it?
You should be able to update with
```bash
$ pip install -U lmn
```
Then please make sure that `lmn --version` shows `0.3.1`

**Comment by richardxd** [comment]
It was fixed and I forgot to reply. Thanks!!
